=== desconocida11/masterjava/src/main/resources/payload.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://javaops.ru"
           xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
           jaxb:version="2.0"
           targetNamespace="http://javaops.ru"
           elementFormDefault="qualified" attributeFormDefault="unqualified"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <xs:element name="Payload">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="Projects">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element ref="Project"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Users">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="User"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Cities">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element ref="City"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Project">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="description"/>
                <xs:sequence maxOccurs="unbounded">
                    <xs:element name="Group">
                        <xs:complexType>
                            <xs:attribute name="name" type="xs:ID" use="required"/>
                            <xs:attribute name="type" type="groupType" use="required"/>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="User">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="fullName"/>
            </xs:sequence>
            <xs:attribute type="flagType" name="flag" use="required"/>
            <xs:attribute type="xs:IDREF" name="city" use="required">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:property>
                            <jaxb:baseType name="CityType"/>
                        </jaxb:property>
                    </xs:appinfo>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute type="xs:string" name="email" use="required"/>
            <xs:attribute type="xs:IDREFS" name="group-refs">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:property>
                            <jaxb:baseType name="Project.Group"/>
                        </jaxb:property>
                    </xs:appinfo>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="flagType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="active"/>
            <xs:enumeration value="deleted"/>
            <xs:enumeration value="superuser"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="groupType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="REGISTERING"/>
            <xs:enumeration value="CURRENT"/>
            <xs:enumeration value="FINISHED"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="City" type="cityType"/>

    <xs:complexType name="cityType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

</xs:schema>

=== desconocida11/masterjava/src/test/resources/payload.xml
<Payload xmlns="http://javaops.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://javaops.ru payload.xsd">
    <Projects>
        <Project name="topjava">
            <description>TopJava</description>
            <Group name="topjava22" type="FINISHED"/>
            <Group name="topjava23" type="CURRENT"/>
        </Project>
        <Project name="masterjava">
            <description>MasterJava</description>
            <Group name="masterjava03" type="CURRENT"/>
        </Project>
        <Project name="basejava">
            <description>BaseJava</description>
            <Group name="basejava01" type="REGISTERING"/>
        </Project>
    </Projects>

    <Users>
        <User flag="active" city="kiv" email="gmail@gmail.com" group-refs="basejava01 masterjava03">
            <fullName>Full Name</fullName>
        </User>
        <User flag="superuser" city="spb" email="admin@javaops.ru" group-refs="topjava23">
            <fullName>Admin</fullName>
        </User>
        <User flag="deleted" city="spb" email="mail@yandex.ru" group-refs="basejava01">
            <fullName>Deleted</fullName>
        </User>
    </Users>
    <Cities>
        <City id="spb">Санкт-Петербург</City>
        <City id="kiv">Киев</City>
        <City id="mnsk">Минск</City>
    </Cities>
</Payload>
